### ISSUE TITLE
Plugin breaks WP menu box toggle

### ISSUE THREAD

**Issue by ghost** [rogerlos/cmb2-metatabs-options#6]
The standard WP menu box toggle (see picture) does not work with the plugin.
![unbenannt](https://cloud.githubusercontent.com/assets/17730312/15454279/8af54792-2034-11e6-8cc6-3ffb97c62024.PNG)

**Comment by mac2net** [comment]
Happening to me too.

**Comment by rogerlos** [comment]
Can you provide me with your browser info, and what errors might be appearing on the JS console, if any?

**Comment by Kaleidosko** [comment]
I can confirm this...
Its an ajax problem:

correct "close" request looks like this:
```
action=closed-postboxes&
closed=optionen_metabox&
hidden=postexcerpt%2Ctrackbacksdiv%2Cpostcustom%2Ccommentstatusdiv%2Ccommentsdiv%2Cslugdiv%2Cauthordiv&
closedpostboxesnonce=29958979d235&
page=post
```

But within the option page the request looks like this:
```
action=closed-postboxes&
closed=&
hidden=opt_pics_a%2Copt_pics_b&
page=postbox-container
```

It seems there is missing something.

BTW: reordering and hiding boxes is also affected... everything what needs an admin-ajax.php answer (which returns Code 403 instead of 200).

Would be awesome, if you can fix this.

Greetings

**Comment by Kaleidosko** [comment]
Oh and I use your plugin as dropIn class... this also requires me to set the jurl also if the file is in the same folder because the wordpress path2url function is not working with the dropIn methode.

**Comment by rogerlos** [comment]
Version 1.2 adds the missing WP nonces. Please let me know if that does not fix this by re-opening this bug.
